# Generated by Django 5.0.2 on 2024-04-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_is_verified_idverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idverification',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='idverification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
