# Generated by Django 5.0.2 on 2024-04-29 03:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_idverification_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idverification',
            name='address',
            field=models.TextField(default='123 Main St'),
        ),
        migrations.AddField(
            model_name='idverification',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='idverification',
            name='name',
            field=models.CharField(default='John Doe', max_length=255),
        ),
    ]
