# Generated by Django 5.0.2 on 2024-04-27 12:39

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_location', models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Pokhara', 'Pokhara')], max_length=100)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('Sedan', 'Sedan'), ('Sports', 'Sports'), ('SUV', 'SUV'), ('EV', 'EV'), ('MPV', 'MPV')], default='Unknown', max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('mileage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('transmission', models.CharField(max_length=50)),
                ('seats', models.IntegerField(default=0)),
                ('luggage', models.IntegerField(default=0)),
                ('fuel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=8)),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('drop_off_date', models.DateTimeField(default=datetime.datetime.now)),
                ('pick_up_date', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.car')),
            ],
        ),
    ]
