# Generated by Django 5.0.2 on 2024-03-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('car_location', models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Pokhara', 'Pokhara')], default='unknown', max_length=100)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('num_seats', models.IntegerField(default=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
