# Generated by Django 5.0.2 on 2024-04-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_drop_off_date_booking_pick_up_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='make',
        ),
        migrations.RemoveField(
            model_name='car',
            name='num_seats',
        ),
        migrations.AddField(
            model_name='car',
            name='company',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='luggage',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='car',
            name='seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
