# Generated by Django 5.0.2 on 2024-04-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_car_make_remove_car_num_seats_car_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_location',
            field=models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Pokhara', 'Pokhara')], max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='luggage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(max_length=50),
        ),
    ]
