# Generated by Django 5.0.2 on 2024-04-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_car_car_location_alter_car_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='company',
        ),
        migrations.AddField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Sports', 'Sports'), ('SUV', 'SUV'), ('EV', 'EV'), ('MPV', 'MPV')], default='Unknown', max_length=20),
        ),
    ]
